"use client";
import React, { useState } from "react";
import { GlassPanel, motionVariants } from "@healthmesh/ui";
import { motion } from "framer-motion";
import { Brain, Activity, Heart, ShieldAlert, Pill, FileText, Download, Share2, RefreshCw, AlertTriangle, ArrowRight, User } from "lucide-react";
import { useStore } from "../../../store/useStore";
import { toast } from "sonner";

export default function ContinuityCapsulePage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const records = useStore(state => state.records);
  const user = useStore(state => state.user);

  const handleRefresh = async () => {
    setIsGenerating(true);
    toast("AI synthesizing latest vault records...");
    await new Promise(r => setTimeout(r, 2000));
    setIsGenerating(false);
    toast.success("Continuity Capsule updated");
  };

  return (
    <div className="p-6 md:p-10 max-w-[1400px] mx-auto min-h-screen">
      <header className="mb-8 flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <motion.div initial="initial" animate="animate" variants={motionVariants.staggerContainer}>
          <motion.div variants={motionVariants.resolveIn} className="flex items-center gap-3 mb-2">
            <div className="p-2 rounded-lg bg-gradient-to-tr from-[#2ED9A3]/20 to-[#29F0E0]/20 border border-[#2ED9A3]/30">
               <Brain className="w-5 h-5 text-[#2ED9A3]" />
            </div>
            <p className="text-[11px] font-mono uppercase tracking-[0.25em] text-[#2ED9A3] flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[#2ED9A3] animate-pulse"/> AI Synthesized
            </p>
          </motion.div>
          <motion.h1 variants={motionVariants.resolveIn} className="text-4xl font-light text-white tracking-tight">Continuity Capsule</motion.h1>
          <motion.p variants={motionVariants.resolveIn} className="text-white/50 text-sm mt-2 max-w-2xl">
            A real-time, cryptographically verified summary of your entire healthcare journey, generated by AI to provide doctors with instant context.
          </motion.p>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="flex gap-3">
          <button onClick={handleRefresh} disabled={isGenerating} className="px-4 py-2.5 rounded-lg border border-white/10 text-white/70 text-sm font-medium hover:bg-white/5 transition-colors flex items-center gap-2 disabled:opacity-50">
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin text-[#29F0E0]' : ''}`} /> 
            {isGenerating ? 'Synthesizing...' : 'Refresh Data'}
          </button>
          <button onClick={() => toast.success("Capsule exported to PDF")} className="px-4 py-2.5 rounded-lg bg-[#2ED9A3]/10 border border-[#2ED9A3]/30 text-[#2ED9A3] text-sm font-medium hover:bg-[#2ED9A3]/20 transition-colors flex items-center gap-2">
            <Download className="w-4 h-4" /> Export PDF
          </button>
        </motion.div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Core Vitals & Summary */}
        <div className="lg:col-span-1 flex flex-col gap-6">
           <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
             <GlassPanel className="p-6">
               <h3 className="text-white/40 uppercase text-[10px] tracking-widest font-mono mb-4">Patient Profile</h3>
               <div className="flex items-center gap-4 mb-6">
                 <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center border border-white/10 text-xl font-medium text-white">
                   {user?.name?.substring(0, 2).toUpperCase() || 'JD'}
                 </div>
                 <div>
                   <h2 className="text-xl text-white font-medium">{user?.name || 'John Doe'}</h2>
                   <p className="text-sm text-white/50 font-mono mt-1">ID: {user?.id || '1111-1111'}</p>
                 </div>
               </div>

               <div className="grid grid-cols-2 gap-4">
                 <div className="p-3 bg-white/5 rounded-lg border border-white/5">
                   <p className="text-white/40 text-xs mb-1">Blood Type</p>
                   <p className="text-white font-medium flex items-center gap-2"><Activity className="w-4 h-4 text-[#FF4D6D]"/> O Positive</p>
                 </div>
                 <div className="p-3 bg-white/5 rounded-lg border border-white/5">
                   <p className="text-white/40 text-xs mb-1">Age / Sex</p>
                   <p className="text-white font-medium flex items-center gap-2"><User className="w-4 h-4 text-[#2E6FFF]"/> 42 / M</p>
                 </div>
               </div>
             </GlassPanel>
           </motion.div>

           <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
             <GlassPanel accentColor="red" className="p-6 border-[#FF4D6D]/20 bg-gradient-to-br from-[#FF4D6D]/5 to-transparent">
               <h3 className="text-[#FF4D6D] uppercase text-[10px] tracking-widest font-mono mb-4 flex items-center gap-2">
                 <ShieldAlert className="w-3.5 h-3.5" /> Critical Alerts
               </h3>
               <div className="space-y-3">
                 <div className="flex gap-3">
                   <div className="w-1.5 h-1.5 rounded-full bg-[#FF4D6D] mt-2 shrink-0 animate-pulse" />
                   <div>
                     <p className="text-white font-medium text-sm">Severe Penicillin Allergy</p>
                     <p className="text-white/50 text-xs mt-0.5">Anaphylactic response documented.</p>
                   </div>
                 </div>
               </div>
             </GlassPanel>
           </motion.div>
        </div>

        {/* AI Synthesis & Timeline */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}>
            <GlassPanel accentColor="green" className="p-0 overflow-hidden relative">
               <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-[#2ED9A3] to-[#29F0E0]" />
               <div className="p-6 border-b border-white/5 bg-white/[0.02]">
                 <h2 className="text-lg font-medium text-white flex items-center gap-2">
                   <Brain className="w-5 h-5 text-[#2ED9A3]" /> AI Executive Summary
                 </h2>
               </div>
               <div className="p-6 text-white/70 leading-relaxed text-sm">
                 <p className="mb-4">
                   Patient is a 42-year-old male with {records.length} recent records available in the Health Vault.
                   Currently monitoring {records.filter(r => r.category.includes('Lab')).length} lab results.
                 </p>
                 <p className="mb-4 text-[#FF4D6D]/90 font-medium">
                   CRITICAL: Patient has a documented severe anaphylactic allergy to Penicillin. All beta-lactam antibiotics should be avoided.
                 </p>
               </div>
            </GlassPanel>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.7 }}>
            <GlassPanel className="p-6">
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-white font-medium flex items-center gap-2">
                  <Activity className="w-5 h-5 text-[#29F0E0]" /> Recent Vault Activity
                </h3>
              </div>

              <div className="relative pl-6 border-l border-white/10 space-y-8">
                 {records.slice(0, 4).map((record, i) => (
                   <div key={record.id} className="relative">
                     <div className={`absolute -left-[29px] top-1 w-3 h-3 rounded-full border-2 border-[#0A0A0A] ${i === 0 ? 'bg-[#2ED9A3] shadow-[0_0_10px_rgba(46,217,163,0.5)]' : 'bg-white/20'}`} />
                     <p className={`text-xs font-mono mb-1 ${i === 0 ? 'text-[#2ED9A3]' : 'text-white/40'}`}>{record.date}</p>
                     <p className="text-white font-medium text-sm">{record.title}</p>
                     <p className="text-white/50 text-xs mt-1">{record.issuer} • {record.category}</p>
                   </div>
                 ))}
                 
                 {records.length === 0 && (
                   <p className="text-white/40 text-sm">No recent records found in the vault.</p>
                 )}
              </div>
            </GlassPanel>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
